# App Configuration
app:
  name:
  version:
  author:

jwt:
  refreshTokenSecret: process.env.REFRESH_TOKEN_SECRET
  accessTokenSecret: process.env.ACCESS_TOKEN_SECRET

server:
  port: 3500

database:
  mongoDB:
    url: process.env.DATABASE_URL
